---
title: 'Aaron Conway Cover Letter'
regarding: ' JAN-2023-3200: Integrated Pulmonary Index during procedural sedation and analgesia: a cluster-randomized trial'
date: today
date-format: long
opening: 'To the editorial committee,'
format: 
    html:
        template: template_blinded.html
        minimal: true
self-contained: true
---

Thank you for permitting us to submit a revision of our manuscript. Please find below a summary of the changes we have made in response to the reviewers' comments.

### Editor's comments

>Thank you for submitting your manuscript, which is of potential interest to JAN authors. We previously noted the prospective registration of the trial and published the protocol. In addition to attending to all the reviewer comments, please can you address the following issues:

>1.  There are some unexplained discrepancies between the Trial registration entry, protocol and final report.   Please go back through these documents carefully.  The information in all three documents should align exactly (similar wording, similar order, same outcomes etc). Any discrepancies should be fully justified and explained using a specific subheading in the manuscript.

*Response*

The outcomes in the protocol and final report were reported consistently. We have reviewed the documents and found no discrepancies. For example, in the protocol the primary outcome is stated as, 'Number of seconds in an alert condition state without an intervention being applied.'. In this manuscript, the primary outcome is reported as, 'The primary outcome was the number of seconds in an alert condition state without an intervention being applied.' Some additional content was included in the manuscript after the primary outcome definition to make it clearer to the reader how the 'alert condition state' would differ between groups that enabled or disabled the Integrated Pulmonary Index feature.

>1.1 Please report ALL outcomes in this manuscript.

*Response*

I assume the editor is referring to our statement in the statistical analysis section that, 'We pre-specified in the protocol that a process evaluation of alarm performance over time during the establishment and stability phases would be conducted. The process evaluation will be reported separately.'. Please note that all the actual outcomes included in the protocol (see section 2.9 Outcomes) were reported in the initial version of this paper. In the protocol, there was an additional section titled, 'Process evaluation'. That section was separate to the actual outcomes. To make this clearer, we have added a section in the paper. It reads:


### Differences between the protocol and this report

We initially planned to collect data from four departments that use procedural sedation in the health service in which this study was conducted. Three of these four departments did not participate because significant challenges associated with workforce shortages arose at the time of data collection and it was decided that staff did not have the capacity to take on participation in research. We pre-specified in the protocol that, in addition to the primary and secondary outcomes, a process evaluation of alarm performance over time during the establishment and stability phases would be conducted. The process evaluation will be reported separately.

>2. Please see the JAN guidance for reporting abstracts. Remove the detailed stats and write the findings as simple statements without any stats.

*Response*

We have revised the results section of the abstract. It now reads:

The number of seconds in an alarm state without intervention was higher in the group that enabled the Integrated Pulmonary Index compared to the group that disabled this feature but this difference did not reach statistical significance. Likewise, the difference between groups for the total alarm duration, total number of alarms and the total number of appropriate alarms was not statistically significant. The number of inappropriate alarms was higher in the group that enabled the Integrated Pulmonary Index, but this estimate was highly imprecise. There was no difference in the odds of an adverse event (measured by the Tracking and Reporting Outcomes of Procedural Sedation tool) occurring between groups. Desaturation events were uncommon and brief in both groups but area under the SpO~2~ 90% desaturation curve scores were lower for the group that enabled the Integrated Pulmonary Index.

### Reviewer 1 {.break}

>I appreciate the opportunity to review this study, which focuses on respiratory depression during procedural sedation. I have several concerns for the authors.

>1) Clinically, PetCO2 is commonly used as a quick and simple respiratory monitoring indicator, while IPI represents the average respiratory status over a period of time and does not promptly reflect short-term respiratory changes. Why was IPI chosen as the primary indicator? Does it hold greater clinical significance than PetCO2? How did PetCO2 levels change in this study?

*Response*

The Integrated Pulmonary Index incorporates PetCO~2~, so its ability to 'reflect short-term respiratory changes' is exactly the same as PetCO~2~.

>2) The clinical familiarity with IPI is much lower compared to SPO2, etc. It is recommended to briefly introduce IPI in the introduction section: the integrated pulmonary index (IPI) utilizes a special algorithm to integrate and simplify four respiratory monitoring indicators, including SpO2, PETCO2, RR, and PR, using a numerical scale from 1 to 10 to represent different respiratory states in patients, with 1 indicating severe respiratory dysfunction and 10 indicating optimal respiratory status.


*Response*

The third paragraph in the introduction provided an overview of the Integrated Pulmonary Index. We have added the statement to additionally emphasise that the IPI ranges from 1 to 10:

"It uses a numerical scale from 1 to 10 to represent different respiratory states, with 1 indicating severe respiratory dysfunction and 10 indicating optimal respiratory status."


>3) In the discussion, it is mentioned that "the total doses of sedative and analgesic medication for many patients were small, with a median dose of only 1mg for midazolam and 50-75mcg for fentanyl". What were the sedation scores for patients after receiving these doses? Were all patients able to complete the examination?

We did not measure sedation scores in this study. In the discussion, we note that:

"Importantly, there was no systematic difference in the doses of sedative and analgesic medication administered between groups, which suggests that the results are not confounded by differences in the sedation protocol or degree of sedation induced."

One component of the tool we used to measure sedation-related adverse events (the TROOPS tool) is 'sedation quality'. We reported in the results section that: 

"There were two intermediate-severity adverse events related to sedation quality in the IPI enabled group."

>4) The occurrence rate of respiratory depression in the study results was very low. This may be due to differences in the sedation protocol used in this study compared to those reported by our team in previous studies (PMID: 36549036; PMID: 37010960; PMID: 38101583). Could the authors discuss the indications for using IPI in different sedation protocols?

*Response*

In the discussion we noted that results may differ if a larger dose of sedative and analgesic medication was administered, but have revised the statement to include references to previous work by the reviewer's team as additional justification that respiratory depression rates may be lower in this study due to the sedation protocol used. The revised statement reads: 

"It is unclear if different results would be observed if there was a larger dose of sedative and analgesic medication administered, which likely would also be associated with a higher number of alarms due to the increased risk of respiratory depression that has been observed in previous studies (Li et al., 2023; Wang, Shen, et al., 2023; Wang, Sheng, et al., 2023)."


### Reviewer 2

>It is observed that the primary outcome was 1.71 (95% CI 0.96 to 3.06), p=0.068, which is quite close to p<0.05, and ‘There was a smaller number of clusters included than we had planned due to the restricted number of sites available at the time of data collection. In addition, the intra-cluster correlation for the primary outcome was also higher (0.03) than we estimated for the sample size calculation.’ Hence, the primary outcome could be statistically significant if the sample size was big enough. Depending on the authors’ judgment of whether 1.71 is considered to have sufficient clinical significance or not, the authors may state the exact p (p=0.068), recommend a further study of a larger sample size, and a suggestive conclusion on the use of the IPI.

*Response*

We changed the results section to indicate that the primary outcome was not statistically significant in accordance with the editor's request to remove numerical results and statistics in accordance with journal guidance. The revised text reads:

"The number of seconds in an alarm state without intervention was higher in the group that enabled the Integrated Pulmonary Index compared to the group that disabled this feature but this difference did not reach statistical significance."

>As most readers of this journal may not have much statistical knowledge on the interpretation of advanced regression methods, for Table 3, a footnote on the interpretation of the coefficients of Negative binomial component and Zero component should be provided.

*Response*

I do not believe that footnotes are permitted for this journal. The following additional explanation about the interpretation of the coefficients (we presented as odds ratio and incidence rate ratio) from the negative binomial and zero components of the models has been added to the statistical analysis section:

"The two parts of the zero-inflated model we used were a logit model to model which of the two processes the zero outcome was associated with (reported as odds ratio), and a negative binomial model for the count process (reported as incidence rate ratio). This analysis was conducted using the `mixed_model` function from the GLMMadaptive R package (Rizopoulos, 2023). Odds ratios produced by the zero part tell us about the factors influencing whether a patient had an alarm at all, with an odds ratio above 1 for this analysis meaning that enabling the IPI increases the likelihood of having no alarms at all. For the count part of the model, an incidence rate ratio greater than 1 indicates that enabling the IPI increases the number of alarms."

>For Figure 1, I cannot understand the meaning of ‘Received allocated intervention (n=6, cluster size’ in the box for ‘Allocated to Control’.

*Response*

Thank you for noticing this mistake. There was text missing from the box. The figure has been corrected.




